# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f47482f90a9c8983ae3d74b3aca07d50db6feabd2b841d7a71c4dc1170286bc87ab06f2f4d36a0755ce4505d74b0266614df19a623b9774186c1123788779ce8

test:
  secret_key_base: 29f4d29283e8578af0f02377555945de6015f2ac50f2816e97a2a672f880d4ccb8b188418f170a39ab957ca364e8ab0e6a9563739936d4e351619b73ec177a79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
